### ISSUE TITLE
Potential update issue

### ISSUE THREAD

**Issue by jeeftor** [deanishe/alfred-workflow#104]
**Version 1.21.1**

I'm having an issue (i believe) with the update check working correctly.  I'm running

`python update.py check jeeftor/alfredToday 3.1.0`

And the output gives me a not very nice answer:
```
08:03:14 update.py:309 DEBUG    Retrieving releases list from `https://api.github.com/repos/jeeftor/alfredToday/releases` ...
08:03:14 workflow.py:1799 DEBUG    Loading cached data from : /Users/jstein/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/org.jeef.today/gh-releases-jeeftor-alfredToday.cpickle
08:03:14 update.py:320 DEBUG    Release : {u'body': u'Updated document templates\r\nAdded a try/catch for a case where somebody has an out of date settings file.', u'tag_name': u'v4.1.0', u'assets_url': u'https://api.github.com/repos/jeeftor/alfredToday/releases/4163248/assets', u'name': u'Enhanced Template and protection', u'upload_url': u'https://uploads.github.com/repos/jeeftor/alfredToday/releases/4163248/assets{?name,label}', u'author': {u'following_url': u'https://api.github.com/users/jeeftor/following{/other_user}', u'gists_url': u'https://api.github.com/users/jeeftor/gists{/gist_id}', u'organizations_url': u'https://api.github.com/users/jeeftor/orgs', u'url': u'https://api.github.com/users/jeeftor', u'events_url': u'https://api.github.com/users/jeeftor/events{/privacy}', u'html_url': u'https://github.com/jeeftor', u'subscriptions_url': u'https://api.github.com/users/jeeftor/subscriptions', u'avatar_url': u'https://avatars.githubusercontent.com/u/6491743?v=3', u'repos_url': u'https://api.github.com/users/jeeftor/repos', u'received_events_url': u'https://api.github.com/users/jeeftor/received_events', u'gravatar_id': u'', u'starred_url': u'https://api.github.com/users/jeeftor/starred{/owner}{/repo}', u'site_admin': False, u'login': u'jeeftor', u'type': u'User', u'id': 6491743, u'followers_url': u'https://api.github.com/users/jeeftor/followers'}, u'url': u'https://api.github.com/repos/jeeftor/alfredToday/releases/4163248', u'created_at': u'2016-09-18T18:11:09Z', u'target_commitish': u'master', u'html_url': u'https://github.com/jeeftor/alfredToday/releases/tag/v4.1.0', u'zipball_url': u'https://api.github.com/repos/jeeftor/alfredToday/zipball/v4.1.0', u'published_at': u'2016-09-18T18:12:47Z', u'draft': False, u'prerelease': False, u'tarball_url': u'https://api.github.com/repos/jeeftor/alfredToday/tarball/v4.1.0', u'id': 4163248, u'assets': [{u'content_type': u'application/octet-stream', u'name': u'Alfred_Today-4.1.0.alfredworkflow', u'url': u'https://api.github.com/repos/jeeftor/alfredToday/releases/assets/2332084', u'created_at': u'2016-09-18T18:12:40Z', u'browser_download_url': u'https://github.com/jeeftor/alfredToday/releases/download/v4.1.0/Alfred_Today-4.1.0.alfredworkflow', u'updated_at': u'2016-09-18T18:12:44Z', u'state': u'uploaded', u'uploader': {u'following_url': u'https://api.github.com/users/jeeftor/following{/other_user}', u'gists_url': u'https://api.github.com/users/jeeftor/gists{/gist_id}', u'organizations_url': u'https://api.github.com/users/jeeftor/orgs', u'url': u'https://api.github.com/users/jeeftor', u'events_url': u'https://api.github.com/users/jeeftor/events{/privacy}', u'html_url': u'https://github.com/jeeftor', u'subscriptions_url': u'https://api.github.com/users/jeeftor/subscriptions', u'avatar_url': u'https://avatars.githubusercontent.com/u/6491743?v=3', u'repos_url': u'https://api.github.com/users/jeeftor/repos', u'received_events_url': u'https://api.github.com/users/jeeftor/received_events', u'gravatar_id': u'', u'starred_url': u'https://api.github.com/users/jeeftor/starred{/owner}{/repo}', u'site_admin': False, u'login': u'jeeftor', u'type': u'User', u'id': 6491743, u'followers_url': u'https://api.github.com/users/jeeftor/followers'}, u'download_count': 9, u'label': None, u'id': 2332084, u'size': 5280546}]}
Traceback (most recent call last):
  File "update.py", line 426, in <module>
    check_update(github_slug, version, prereleases)
  File "update.py", line 350, in check_update
    releases = get_valid_releases(github_slug, prereleases)
  File "update.py", line 322, in get_valid_releases
    release = _validate_release(release)
  File "update.py", line 238, in _validate_release
    alf3 = wf().alfred_version.major == 3
  File "/Users/jstein/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/workflow/workflow.py", line 1136, in alfred_version
    return Version(self.alfred_env.get('version'))
  File "/Users/jstein/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/workflow/update.py", line 89, in __init__
    self._parse(str)0
  File "/Users/jstein/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/workflow/update.py", line 92, in _parse
    if vstr.startswith('v'):
AttributeError: 'NoneType' object has no attribute 'starts with'
```8:03:14 update.py:309 DEBUG    Retrieving releases list from `https://api.github.com/repos/jeeftor/alfredToday/releases` ...
08:03:14 workflow.py:1799 DEBUG    Loading cached data from : /Users/jstein/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/org.jeef.today/gh-releases-jeeftor-alfredToday.cpickle
08:03:14 update.py:320 DEBUG    Release : {u'body': u'Updated document templates\r\nAdded a try/catch for a case where somebody has an out of date settings file.', u'tag_name': u'v4.1.0', u'assets_url': u'https://api.github.com/repos/jeeftor/alfredToday/releases/4163248/assets', u'name': u'Enhanced Template and protection', u'upload_url': u'https://uploads.github.com/repos/jeeftor/alfredToday/releases/4163248/assets{?name,label}', u'author': {u'following_url': u'https://api.github.com/users/jeeftor/following{/other_user}', u'gists_url': u'https://api.github.com/users/jeeftor/gists{/gist_id}', u'organizations_url': u'https://api.github.com/users/jeeftor/orgs', u'url': u'https://api.github.com/users/jeeftor', u'events_url': u'https://api.github.com/users/jeeftor/events{/privacy}', u'html_url': u'https://github.com/jeeftor', u'subscriptions_url': u'https://api.github.com/users/jeeftor/subscriptions', u'avatar_url': u'https://avatars.githubusercontent.com/u/6491743?v=3', u'repos_url': u'https://api.github.com/users/jeeftor/repos', u'received_events_url': u'https://api.github.com/users/jeeftor/received_events', u'gravatar_id': u'', u'starred_url': u'https://api.github.com/users/jeeftor/starred{/owner}{/repo}', u'site_admin': False, u'login': u'jeeftor', u'type': u'User', u'id': 6491743, u'followers_url': u'https://api.github.com/users/jeeftor/followers'}, u'url': u'https://api.github.com/repos/jeeftor/alfredToday/releases/4163248', u'created_at': u'2016-09-18T18:11:09Z', u'target_commitish': u'master', u'html_url': u'https://github.com/jeeftor/alfredToday/releases/tag/v4.1.0', u'zipball_url': u'https://api.github.com/repos/jeeftor/alfredToday/zipball/v4.1.0', u'published_at': u'2016-09-18T18:12:47Z', u'draft': False, u'prerelease': False, u'tarball_url': u'https://api.github.com/repos/jeeftor/alfredToday/tarball/v4.1.0', u'id': 4163248, u'assets': [{u'content_type': u'application/octet-stream', u'name': u'Alfred_Today-4.1.0.alfredworkflow', u'url': u'https://api.github.com/repos/jeeftor/alfredToday/releases/assets/2332084', u'created_at': u'2016-09-18T18:12:40Z', u'browser_download_url': u'https://github.com/jeeftor/alfredToday/releases/download/v4.1.0/Alfred_Today-4.1.0.alfredworkflow', u'updated_at': u'2016-09-18T18:12:44Z', u'state': u'uploaded', u'uploader': {u'following_url': u'https://api.github.com/users/jeeftor/following{/other_user}', u'gists_url': u'https://api.github.com/users/jeeftor/gists{/gist_id}', u'organizations_url': u'https://api.github.com/users/jeeftor/orgs', u'url': u'https://api.github.com/users/jeeftor', u'events_url': u'https://api.github.com/users/jeeftor/events{/privacy}', u'html_url': u'https://github.com/jeeftor', u'subscriptions_url': u'https://api.github.com/users/jeeftor/subscriptions', u'avatar_url': u'https://avatars.githubusercontent.com/u/6491743?v=3', u'repos_url': u'https://api.github.com/users/jeeftor/repos', u'received_events_url': u'https://api.github.com/users/jeeftor/received_events', u'gravatar_id': u'', u'starred_url': u'https://api.github.com/users/jeeftor/starred{/owner}{/repo}', u'site_admin': False, u'login': u'jeeftor', u'type': u'User', u'id': 6491743, u'followers_url': u'https://api.github.com/users/jeeftor/followers'}, u'download_count': 9, u'label': None, u'id': 2332084, u'size': 5280546}]}
Traceback (most recent call last):
  File "update.py", line 426, in <module>
    check_update(github_slug, version, prereleases)
  File "update.py", line 350, in check_update
    releases = get_valid_releases(github_slug, prereleases)
  File "update.py", line 322, in get_valid_releases
    release = _validate_release(release)
  File "update.py", line 238, in _validate_release
    alf3 = wf().alfred_version.major == 3
  File "/Users/jstein/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/workflow/workflow.py", line 1136, in alfred_version
    return Version(self.alfred_env.get('version'))
  File "/Users/jstein/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/workflow/update.py", line 89, in __init__
    self._parse(vstr)
  File "/Users/jstein/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/workflow/update.py", line 92, in _parse
    if vstr.startswith('v'):
AttributeError: 'NoneType' object has no attribute 'startswith'08:03:14 update.py:309 DEBUG    Retrieving releases list from `https://api.github.com/repos/jeeftor/alfredToday/releases` ...
08:03:14 workflow.py:1799 DEBUG    Loading cached data from : /Users/jstein/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/org.jeef.today/gh-releases-jeeftor-alfredToday.cpickle
08:03:14 update.py:320 DEBUG    Release : {u'body': u'Updated document templates\r\nAdded a try/catch for a case where somebody has an out of date settings file.', u'tag_name': u'v4.1.0', u'assets_url': u'https://api.github.com/repos/jeeftor/alfredToday/releases/4163248/assets', u'name': u'Enhanced Template and protection', u'upload_url': u'https://uploads.github.com/repos/jeeftor/alfredToday/releases/4163248/assets{?name,label}', u'author': {u'following_url': u'https://api.github.com/users/jeeftor/following{/other_user}', u'gists_url': u'https://api.github.com/users/jeeftor/gists{/gist_id}', u'organizations_url': u'https://api.github.com/users/jeeftor/orgs', u'url': u'https://api.github.com/users/jeeftor', u'events_url': u'https://api.github.com/users/jeeftor/events{/privacy}', u'html_url': u'https://github.com/jeeftor', u'subscriptions_url': u'https://api.github.com/users/jeeftor/subscriptions', u'avatar_url': u'https://avatars.githubusercontent.com/u/6491743?v=3', u'repos_url': u'https://api.github.com/users/jeeftor/repos', u'received_events_url': u'https://api.github.com/users/jeeftor/received_events', u'gravatar_id': u'', u'starred_url': u'https://api.github.com/users/jeeftor/starred{/owner}{/repo}', u'site_admin': False, u'login': u'jeeftor', u'type': u'User', u'id': 6491743, u'followers_url': u'https://api.github.com/users/jeeftor/followers'}, u'url': u'https://api.github.com/repos/jeeftor/alfredToday/releases/4163248', u'created_at': u'2016-09-18T18:11:09Z', u'target_commitish': u'master', u'html_url': u'https://github.com/jeeftor/alfredToday/releases/tag/v4.1.0', u'zipball_url': u'https://api.github.com/repos/jeeftor/alfredToday/zipball/v4.1.0', u'published_at': u'2016-09-18T18:12:47Z', u'draft': False, u'prerelease': False, u'tarball_url': u'https://api.github.com/repos/jeeftor/alfredToday/tarball/v4.1.0', u'id': 4163248, u'assets': [{u'content_type': u'application/octet-stream', u'name': u'Alfred_Today-4.1.0.alfredworkflow', u'url': u'https://api.github.com/repos/jeeftor/alfredToday/releases/assets/2332084', u'created_at': u'2016-09-18T18:12:40Z', u'browser_download_url': u'https://github.com/jeeftor/alfredToday/releases/download/v4.1.0/Alfred_Today-4.1.0.alfredworkflow', u'updated_at': u'2016-09-18T18:12:44Z', u'state': u'uploaded', u'uploader': {u'following_url': u'https://api.github.com/users/jeeftor/following{/other_user}', u'gists_url': u'https://api.github.com/users/jeeftor/gists{/gist_id}', u'organizations_url': u'https://api.github.com/users/jeeftor/orgs', u'url': u'https://api.github.com/users/jeeftor', u'events_url': u'https://api.github.com/users/jeeftor/events{/privacy}', u'html_url': u'https://github.com/jeeftor', u'subscriptions_url': u'https://api.github.com/users/jeeftor/subscriptions', u'avatar_url': u'https://avatars.githubusercontent.com/u/6491743?v=3', u'repos_url': u'https://api.github.com/users/jeeftor/repos', u'received_events_url': u'https://api.github.com/users/jeeftor/received_events', u'gravatar_id': u'', u'starred_url': u'https://api.github.com/users/jeeftor/starred{/owner}{/repo}', u'site_admin': False, u'login': u'jeeftor', u'type': u'User', u'id': 6491743, u'followers_url': u'https://api.github.com/users/jeeftor/followers'}, u'download_count': 9, u'label': None, u'id': 2332084, u'size': 5280546}]}
Traceback (most recent call last):
  File "update.py", line 426, in <module>
    check_update(github_slug, version, prereleases)
  File "update.py", line 350, in check_update
    releases = get_valid_releases(github_slug, prereleases)
  File "update.py", line 322, in get_valid_releases
    release = _validate_release(release)
  File "update.py", line 238, in _validate_release
    alf3 = wf().alfred_version.major == 3
  File "/Users/jstein/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/workflow/workflow.py", line 1136, in alfred_version
    return Version(self.alfred_env.get('version'))
  File "/Users/jstein/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/workflow/update.py", line 89, in __init__
    self._parse(vstr)
  File "/Users/jstein/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/workflow/update.py", line 92, in _parse
    if vstr.startswith('v'):
AttributeError: 'NoneType' object has no attribute 'startswith'08:03:14 update.py:309 DEBUG    Retrieving releases list from `https://api.github.com/repos/jeeftor/alfredToday/releases` ...
08:03:14 workflow.py:1799 DEBUG    Loading cached data from : /Users/jstein/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/org.jeef.today/gh-releases-jeeftor-alfredToday.cpickle
08:03:14 update.py:320 DEBUG    Release : {u'body': u'Updated document templates\r\nAdded a try/catch for a case where somebody has an out of date settings file.', u'tag_name': u'v4.1.0', u'assets_url': u'https://api.github.com/repos/jeeftor/alfredToday/releases/4163248/assets', u'name': u'Enhanced Template and protection', u'upload_url': u'https://uploads.github.com/repos/jeeftor/alfredToday/releases/4163248/assets{?name,label}', u'author': {u'following_url': u'https://api.github.com/users/jeeftor/following{/other_user}', u'gists_url': u'https://api.github.com/users/jeeftor/gists{/gist_id}', u'organizations_url': u'https://api.github.com/users/jeeftor/orgs', u'url': u'https://api.github.com/users/jeeftor', u'events_url': u'https://api.github.com/users/jeeftor/events{/privacy}', u'html_url': u'https://github.com/jeeftor', u'subscriptions_url': u'https://api.github.com/users/jeeftor/subscriptions', u'avatar_url': u'https://avatars.githubusercontent.com/u/6491743?v=3', u'repos_url': u'https://api.github.com/users/jeeftor/repos', u'received_events_url': u'https://api.github.com/users/jeeftor/received_events', u'gravatar_id': u'', u'starred_url': u'https://api.github.com/users/jeeftor/starred{/owner}{/repo}', u'site_admin': False, u'login': u'jeeftor', u'type': u'User', u'id': 6491743, u'followers_url': u'https://api.github.com/users/jeeftor/followers'}, u'url': u'https://api.github.com/repos/jeeftor/alfredToday/releases/4163248', u'created_at': u'2016-09-18T18:11:09Z', u'target_commitish': u'master', u'html_url': u'https://github.com/jeeftor/alfredToday/releases/tag/v4.1.0', u'zipball_url': u'https://api.github.com/repos/jeeftor/alfredToday/zipball/v4.1.0', u'published_at': u'2016-09-18T18:12:47Z', u'draft': False, u'prerelease': False, u'tarball_url': u'https://api.github.com/repos/jeeftor/alfredToday/tarball/v4.1.0', u'id': 4163248, u'assets': [{u'content_type': u'application/octet-stream', u'name': u'Alfred_Today-4.1.0.alfredworkflow', u'url': u'https://api.github.com/repos/jeeftor/alfredToday/releases/assets/2332084', u'created_at': u'2016-09-18T18:12:40Z', u'browser_download_url': u'https://github.com/jeeftor/alfredToday/releases/download/v4.1.0/Alfred_Today-4.1.0.alfredworkflow', u'updated_at': u'2016-09-18T18:12:44Z', u'state': u'uploaded', u'uploader': {u'following_url': u'https://api.github.com/users/jeeftor/following{/other_user}', u'gists_url': u'https://api.github.com/users/jeeftor/gists{/gist_id}', u'organizations_url': u'https://api.github.com/users/jeeftor/orgs', u'url': u'https://api.github.com/users/jeeftor', u'events_url': u'https://api.github.com/users/jeeftor/events{/privacy}', u'html_url': u'https://github.com/jeeftor', u'subscriptions_url': u'https://api.github.com/users/jeeftor/subscriptions', u'avatar_url': u'https://avatars.githubusercontent.com/u/6491743?v=3', u'repos_url': u'https://api.github.com/users/jeeftor/repos', u'received_events_url': u'https://api.github.com/users/jeeftor/received_events', u'gravatar_id': u'', u'starred_url': u'https://api.github.com/users/jeeftor/starred{/owner}{/repo}', u'site_admin': False, u'login': u'jeeftor', u'type': u'User', u'id': 6491743, u'followers_url': u'https://api.github.com/users/jeeftor/followers'}, u'download_count': 9, u'label': None, u'id': 2332084, u'size': 5280546}]}
Traceback (most recent call last):
  File "update.py", line 426, in <module>
    check_update(github_slug, version, prereleases)
  File "update.py", line 350, in check_update
    releases = get_valid_releases(github_slug, prereleases)
  File "update.py", line 322, in get_valid_releases
    release = _validate_release(release)
  File "update.py", line 238, in _validate_release
    alf3 = wf().alfred_version.major == 3
  File "/Users/jstein/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/workflow/workflow.py", line 1136, in alfred_version
    return Version(self.alfred_env.get('version'))
  File "/Users/jstein/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/workflow/update.py", line 89, in __init__
    self._parse(vstr)
  File "/Users/jstein/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/org.jeef.today/workflow/update.py", line 92, in _parse
    if vstr.startswith('v'):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by jeeftor** [comment]
I'm trying to track down the bug in the code but i'm not having much luck...

**Comment by idpaterson** [comment]
Are you running that from within Alfred or from the terminal? It looks like it is not getting the Alfred environment variables. What is your Alfred version?

**Comment by jeeftor** [comment]
Hmm....

Son in my case:

```
  @property
    def alfred_version(self):
        """Alfred version as :class:`~workflow.update.Version` object."""
        from update import Version
        return Version(self.alfred_env.get('version') or '3.1.1')
```

fixed the issue.  Should i not be able to run this from command line?

**Comment by jeeftor** [comment]
Yea -> I just hardcoded an alfred version into the update script and now its working.... so I guess it shouldn't be able to be run from terminal?

**Comment by idpaterson** [comment]
I've had the same problem, though rather than hardcoding you could populate the environment variable when running the script:
```
alfred_version=3.0.0 python update.py check jeeftor/alfredToday 3.1.0
```

It would be good to check any values derived from `alfred_env()` or maybe provide sensible defaults to avoid throwing errors when run outside of Alfred.

**Comment by deanishe** [comment]
Now that envvars are a big part of Alfred, I usually write a shell script I can source to create an Alfred-like environment in the shell.

I should probably add a sample to the docs.
