### ISSUE TITLE
Keychain error after updating to MacOS Mojave

### ISSUE THREAD

**Issue by Garulf** [deanishe/alfred-workflow#138]
When attempting to access a saved keychain on MacOS Mojave i get an unknown keychainError.
The keychain API worked fine before updating.

Trace back:
`18:02:14 workflow.py:2074 ERROR    Unknown Keychain error :
Traceback (most recent call last):
  File "/Users/Billy/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.9A658781-F5D9-48E8-B753-52E59E336942/workflow/workflow.py", line 2067, in run
    func(self)
  File "main.py", line 33, in main
    api_key = wf.get_password('youtube_api_key')
  File "/Users/Billy/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.9A658781-F5D9-48E8-B753-52E59E336942/workflow/workflow.py", line 2442, in get_password
    account, '-g')
  File "/Users/Billy/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.9A658781-F5D9-48E8-B753-52E59E336942/workflow/workflow.py", line 2817, in _call_security
    raise err
KeychainError: Unknown Keychain error `

**Comment by Garulf** [comment]
Seems to be an issue with the command line tool being used in method “_call_security” on line 2806. 

The MacOS command line tool security isn’t displaying a password even though the -g flag is set. 

I tried the command manually with no results or error. 

`security find-generic-password -s 'garulf.youtube.plugin' -a 'youtube_api_key' -g `

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by deanishe** [comment]
I don't have Mojave to investigate.

It's likely the sandbox. Can you try granting "Full Disk Access" in the Security & Privacy prefs?

**Comment by deanishe** [comment]
Sorry, that could have been clearer.

Grant access to Alfred, not the `security` program.

**Comment by Garulf** [comment]
I found the issue, I was testing my code remotely via SSH.

Finally got some time to sit at my machine and behold it works!
It seems security does not work under SSH even with root permissions.

**Comment by deanishe** [comment]
> It seems security does not work under SSH even with root permissions

FYI, the library is only really designed to run within Alfred, not in a shell or in any other environment.

In many cases, it does work because of old code that pre-dates the introduction of environment variables in Alfred, but broadly speaking, any issue that occurs when the library is used outside of Alfred is invalid.
