### ISSUE TITLE
Run with error

### ISSUE THREAD

**Issue by peng051410** [deanishe/alfred-workflow#140]
I use this lib to write workflow, but got this error:
`18:30:34 workflow.py:2074 ERROR    not well-formed (invalid token): line 80, column 20
Traceback (most recent call last):
  File "/Users/tomyli/Nustore/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A1DC8BC3-6CCE-450E-9061-B94DD28A1B34/workflow/workflow.py", line 2053, in run
    if self.version:
  File "/Users/tomyli/Nustore/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A1DC8BC3-6CCE-450E-9061-B94DD28A1B34/workflow/workflow.py", line 1175, in version
    version = self.info.get('version')
  File "/Users/tomyli/Nustore/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A1DC8BC3-6CCE-450E-9061-B94DD28A1B34/workflow/workflow.py", line 1087, in info
    self._load_info_plist()
  File "/Users/tomyli/Nustore/Alfred/Alfred.alfredpreferences/workflows/user.workflow.A1DC8BC3-6CCE-450E-9061-B94DD28A1B34/workflow/workflow.py", line 2766, in _load_info_plist
    self._info = plistlib.readPlist(self.workflowfile('info.plist'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)
ExpatError: not well-formed (invalid token): line 80, column 20
`
What should i do?

**Comment by deanishe** [comment]
Check your `info.plist`. That says it's invalid.

**Comment by peng051410** [comment]
Thanks!
